{% set name = "typogrify" %}
{% set version = "2.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typogrify-{{ version }}.tar.gz
  sha256: 8be4668cda434163ce229d87ca273a11922cb1614cb359970b7dc96eed13cb38

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - python >=3.6
    - smartypants >=1.8.3

test:
  imports:
    - typogrify
    - typogrify.packages
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mintchaos/typogrify
  summary: Filters to enhance web typography, including support for Django & Jinja templates
  description: |
    Typogrify provides a set of custom filters that automatically apply various
    transformations to plain text in order to yield typographically-improved
    HTML. While often used in conjunction with Jinja and Django template systems,
    the filters can be used in any environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/mintchaos/typogrify
  dev_url: https://github.com/mintchaos/typogrify

extra:
  recipe-maintainers:
    - pmlandwehr
    - ickc
