travis:
  secure:
    BINSTAR_TOKEN: Rof794n7AjB0qndvVe0KpVstiOM/rY9ZBRrLPIHMh96jAdAd4O8bjPIfoxtToPDxGkIXrxyVr3D6TXimuRmqpplE5c5DK0W92XZHkhhG12ebVsd0Xa6Jszf2i/X/1Q5b943snhxe3EFP3Y1mQwwxv2ETuC68iF4UBnPpWrLj0WClvFRDiUc3yiW2rWJsdxg37M3kwypQLv/UjM3Lnz483bscRMdPokJOUIcKsFrT2UFZoZ9aZur6HZYzPA/rV83VkQBZz1/8/oTAkSM+TcqIC4PKWqMZ5zqIH6g/COmBgClfTSc/H8NczHh2QUvUkGtB3bPmZBjRByY1U3ZNfe7zWlHEZAY2JPpEMFMTk+Zdz3qAQBKsq9D5eDqs4pXcfws4ehgkTcJiQZyIz20Z7W3i+y1guGxZhv05ExMX0lHUbnXyXiL+eXQRuGVlpG59x5xL9X1O+sgtUyA3s5DE75XiqXkU+tOXogam/g7LLYd5riFXrDlpjweQ4sw0XqePnVV+YRGrdNCp1XC2DM/XLo/dQLfS0xURgdZ8GsxI2zVjQZXVdSl6K4QhFG+yUaO5HJlJMdLc82zyfbup2gbkZVkOCZoYio5HxcpVK0bQnOaUWKU3YQGInZ7HiEaUFZZ98inPcmy15ZPlrc0AqL+nKnaa/DHqQOz9T/dgMGddJyvBXYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
