travis:
  secure:
    BINSTAR_TOKEN: JpMU7IvcRv3mN7wSjuWYF9owaEzyzoLWnH032aYHvFtAd5lAnO1fdlGLjPxdiiDNhwS4g4+JovIYm/8eimTIuNHNkh21Ief0shj/YgzV31vnCIyVq8w0MDhirhBYuJtO7SkIuy/4xvDrpgUSiKgmWLdOC2hWJImg4O3cKUa2h7B9yXkENTUKukh5e9u49e9VC5pyzpyq/22sgLWlLOoouMSH1D63o34A9HjD/NSQJxUzrFf7aMEK55deJW5wgzzY91S4/SRTmo2ReyFy8kHWf2iGia5appEvjNnyBgSqKWxDstPBR+ObGg6ezS/pCqolZEqAiBY+w08a898ZQmlRYoAG9q9S2r9uvB1QF+A7BV16z4/AU3C5VCfy9t335uwHMNoGRr/sq8MvVbxdpOaeGKjUjFan6MS/aCpVgziHQ4C1PuXxhAAYex9QP9TZJqTiBn+ovroW3PWXpyzBAfwmezxy2BakiyvrIQbCkpGpWtPy0olyiD5EA7kyKvvb1m1FpRsG6IpGoEZ87x+gdO5R8L6bLB0Q7IYg6ZT+mD3T5te1C2IGkrxsP/LTMhfLMOhHe29YMvrTJpVM2KvTjeB3SH8ivA83pbZHxM5W+kyOs4kcHZwERWZTsIyAAeQEYsHp6sfmu+tNS9aZONDf4Moi11U5e8m3KUxO/jTO7OjGUjM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
