travis:
  secure:
    BINSTAR_TOKEN: sWkAYMGY5SOi1qvaaYbxLLr8E5sTtDKTsgq6qS6dSYwTet70I5RYYQoA6seYQIKTOLQGSFneWMDtblUuGHG4I9eLgVOqu7NliltVPiqdNSmpeSHPwhujsz/Bu5AI/waL2jfSHgDI3lE3aebViW3NJr/hqFTQNwluy8ACsSjv4JsZXbRGeFb/yK+i/RmN8jZ7xMuCGl23+xU/8J9+SoRs0drIOwmSNkQlUQ6IojHUr2La9Bvxw8TxGaockn3E3ihG0T1k+UsrrKuTTG0SPe1jwDMudT6qHbe3Zw88OYKYquo7z/3+u0WK4bJ7tA0xLqCL85De0rSBJr/gLbTteqHoIEtj+qXfgYWKhxCoYp/SIgoIFxc7FXOfGygHVU9s0XDG+zbdHdOk3QiF1A1/BO1Sl6mgM9xsdk2Ol3U3ZeJA/LBMsi6+TW4TbtCaOCVsRe1+W1x3yeC4w8Kjf6QwD85lpacoPLE4vCbBOeWX8+SlKN2qJqBA/rv+VzdFLoWs6luB/SARqvv4kIq5gMwTZhHghK6IUiX6KPhAFdXuNoBkjQJL6jr7gyuzWFyXKk/gVnjySRR9wQuyRNHfJlcGiXwfLtwAmo1aP5qu3CNBAIWzo7Hs4lpLJvVvC2MAZjN9X/qOzlN1wdamAuZ5qgsrOcekoev4mRPDFac+xWgfCagqpPI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
